//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A4A.SharePoint16.Webparts.TestSiteMapWebpart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class TestSiteMapWebpart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Repeater rep1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "15.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(TestSiteMapWebpart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllblMessage() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblMessage = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblMessage";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control3() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(4, 3);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                <tr>\r\n                     <td>                        \r\n      " +
                    "                  <a href=\'");
            @__ctrl.SetStaticString(1, "\'> ");
            @__ctrl.SetStaticString(2, " </a>\r\n                    </td>\r\n                      <td>\r\n                   " +
                    "       ");
            @__ctrl.SetStaticString(3, "                        \r\n                    </td>\r\n                    \r\n      " +
                    "          </tr>\r\n                \r\n            ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control3);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        public void @__DataBind__control3(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            target.SetDataBoundString(0, global::System.Convert.ToString(DataBinder.Eval(Container.DataItem,"GroupSiteURL"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(1, global::System.Convert.ToString(DataBinder.Eval(Container.DataItem, "GroupName"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(2, global::System.Convert.ToString(DataBinder.Eval(Container.DataItem, "Liaison1"), global::System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlrep1() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            this.rep1 = @__ctrl;
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "rep1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControlTree(global::A4A.SharePoint16.Webparts.TestSiteMapWebpart.TestSiteMapWebpart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.10." +
                        "20/css/jquery.dataTables.min.css\">\r\n<script type=\"text/javascript\" src=\"https://" +
                        "cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js\"></script> \r\n<link rel=\"s" +
                        "tylesheet\" href=\"https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.c" +
                        "ss\">\r\n<script src=\"https://code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\r\n \r" +
                        "\n<style type=\"text/css\" class=\"init\">\r\n   td.details-control {\r\n   background: u" +
                        "rl(\'/_catalogs/masterpage/FuelPortal/img/details_open.png\') no-repeat center cen" +
                        "ter;\r\n   cursor: pointer;\r\n   }\r\n   tr.shown td.details-control {\r\n   background" +
                        ": url(\'/_catalogs/masterpage/FuelPortal/img/details_close.png\') no-repeat center" +
                        " center;\r\n   } \r\n\r\n</style>\r\n\r\n<!--/********************************************" +
                        "********************************************************************************" +
                        "***/\r\n   /** Code form UI tool ***********/\r\n   /*******************************" +
                        "****************************/-->\r\n<!--  Bootstrap css  -->\r\n<style type=\"text/cs" +
                        "s\" media=\"all\">\r\n   .top-buffer { margin-top:10px; }\r\n     .bot-buffer { margin-" +
                        "bottom:10px; margin-right: 10px;}\r\n   .left {float:left !important;}\r\n   .right " +
                        "{float:right !important;}\r\n   .filterlabels{float:left; padding-right: 5px;paddi" +
                        "ng-top: 3px;}\r\n   .article {\r\n        margin-left:20px;\r\n       overflow:visible" +
                        " !important;\r\n    }\r\n       h2 {\r\n    margin-top:0px;\r\n    margin-bottom: 0px;\r\n" +
                        "    }\r\n   table.dataTable td { \r\n    word-wrap: break-word;\r\n} \r\n    .dataTables" +
                        "_wrapper {\r\n    margin-top: 2em !important;\r\n    }   \r\n</style>                 " +
                        "     \r\n\r\n"));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblMessage();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<table id=\"SiteMapDT\" class=\"display\" border=\"0\" cellspacing=\"0\" cellpadding=" +
                        "\"0\">\r\n    <thead>\r\n        <tr>\r\n             <th>Group</th> \r\n            <th>L" +
                        "iaison</th> \r\n            \r\n        </tr>\r\n    </thead>\r\n    <tbody> \r\n        "));
            global::System.Web.UI.WebControls.Repeater @__ctrl2;
            @__ctrl2 = this.@__BuildControlrep1();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
    </tbody> 
</table>



<script>

    //Setting the search for datatable
    $('#SiteMapDT thead th').each(function () {
        var title = $('#SiteMapDT thead th').eq($(this).index()).text();
        if (title.toLowerCase().indexOf(""detail"") < 0 && title.toLowerCase().indexOf(""edit"") < 0) {
            $(this).html('<input type=""text"" placeholder=""Search ' + title + '"" style=""float:left;"" />');
        }
        else {
            $(this).html('');
        }
    });

    $(document).ready(function () {
     
        //Setting the DataTable -  // DataTable
        var table = $(""#SiteMapDT"").DataTable({
            ""paging"": false, 
            ""columns"": [
                null,
                null]
        });
         

        // Apply the search
        table.columns().eq(0).each(function (colIdx) {
            
            $('input', table.column(colIdx).header()).on('keyup change', function () {
                table
                    .column(colIdx)
                    .search(this.value)
                    .draw();
            });
        });
          
    });
</script>



"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
