//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A4A.UM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirtySlotHolderOperator
    {
        public string SlotNo { get; set; }
        public int AirportId { get; set; }
        public Nullable<bool> ToBeDeleted { get; set; }
    }
}
