//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockoutMVC.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_Report_Role_Mapping
    {
        public decimal CommitteeRoleID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> RoleID { get; set; }
    }
}
