//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockoutMVC.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_Report_Council_Taxonomy
    {
        public decimal CommitteeID { get; set; }
        public string Council { get; set; }
        public string LyrisShortDescription { get; set; }
        public Nullable<decimal> Rank { get; set; }
    }
}
