//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockoutMVC.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.GroupAdmins = new HashSet<GroupAdmin>();
            this.MeetingLists = new HashSet<MeetingList>();
            this.UserGroups = new HashSet<UserGroup>();
            this.Group1 = new HashSet<Group>();
            this.Groups = new HashSet<Group>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public bool IsOpenEnrollment { get; set; }
        public int AppliesToSiteId { get; set; }
        public string LyrisListName { get; set; }
        public string LyrisShortDescription { get; set; }
        public string LyrisListType { get; set; }
        public string GroupSiteUrl { get; set; }
        public bool IsCommittee { get; set; }
        public bool IsChildGroup { get; set; }
        public int ParentGroupId { get; set; }
        public Nullable<int> CouncilParentId { get; set; }
        public bool IsSecurityGroup { get; set; }
    
        public virtual GroupType GroupType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupAdmin> GroupAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingList> MeetingLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
    }
}
