//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockoutMVC.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATA_MembershipEntities : DbContext
    {
        public ATA_MembershipEntities()
            : base("name=ATA_MembershipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activity_ActivityTopic> Activity_ActivityTopic { get; set; }
        public virtual DbSet<Activity_ActivityType> Activity_ActivityType { get; set; }
        public virtual DbSet<ActivityTopic> ActivityTopics { get; set; }
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<AppliesToSite> AppliesToSites { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyCategory> CompanyCategories { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EmailsOnlyManagedInLyri> EmailsOnlyManagedInLyris { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<FuelsCompanyType> FuelsCompanyTypes { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupAdmin> GroupAdmins { get; set; }
        public virtual DbSet<GroupType> GroupTypes { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<MeetingGroup> MeetingGroups { get; set; }
        public virtual DbSet<MeetingList> MeetingLists { get; set; }
        public virtual DbSet<MeetingListSourceUser> MeetingListSourceUsers { get; set; }
        public virtual DbSet<MeetingListUser> MeetingListUsers { get; set; }
        public virtual DbSet<MeetingType> MeetingTypes { get; set; }
        public virtual DbSet<MemberType> MemberTypes { get; set; }
        public virtual DbSet<SponsorGroup> SponsorGroups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAddress> UserAddresses { get; set; }
        public virtual DbSet<UserCompany> UserCompanies { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserSponsor> UserSponsors { get; set; }
        public virtual DbSet<X_Report_Council_Taxonomy> X_Report_Council_Taxonomy { get; set; }
        public virtual DbSet<X_Report_Council_Taxonomy_with_Roles> X_Report_Council_Taxonomy_with_Roles { get; set; }
        public virtual DbSet<X_Report_Role_Mapping> X_Report_Role_Mapping { get; set; }
        public virtual DbSet<CommitteeRole> CommitteeRoles { get; set; }
        public virtual DbSet<GroupAdmin2> GroupAdmin2 { get; set; }
        public virtual DbSet<GroupAdmin3> GroupAdmin3 { get; set; }
        public virtual DbSet<UserGroup2> UserGroup2 { get; set; }
    }
}
