//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockoutMVC.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingListUser
    {
        public int MeetingListUserId { get; set; }
        public int UserId { get; set; }
        public string DisplayName { get; set; }
        public bool IsMainGroupUser { get; set; }
        public Nullable<bool> IsA4AUser { get; set; }
        public string Email { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual MeetingList MeetingList { get; set; }
    }
}
